language: node_js

before_script:
  - npm install -g gulp
  - npm install

script:
  - gulp

after_script:
  - touch test.txt

branches:
  only:
    - master

notifications:
  email: false

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: web
  github_token: $GITHUB_TOKEN
  repo: yasinS/preview-live
